Update image to Ubuntu Focal
linuxserver/docker-deluge pull request #110
Opened 2021-02-25 16:16 UTC by foux

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Description:
Current image is using Bionic Ubuntu wich uses a very old `libtorrent-rasterbar9` (version 1.1.5 released on Oct 14 2017). This build has a lot of bugfixes since then. Focal is using the far more up to date `libtorrent-rasterbar9` version 1.1.13 released on april 27 2019

## Benefits of this PR and context:
This PR solves a lot of libtorrent issues

## How Has This Been Tested?
Building and lauching the image with an allready functionning configuration

2021-02-25 16:34 UTC, aptalca requested changes
Thanks for the PR. Please add a changelog entry into readme-vars.yml as well

2021-02-25 16:43 UTC, foux commented
> Thanks for the PR. Please add a changelog entry into readme-vars.yml as well

Sorry for that! Done

2021-02-25 17:02 UTC, aptalca commented
Hmm, bunch of python errors in the ci logs

2021-02-25 17:08 UTC, foux commented
> Hmm, bunch of python errors in the ci logs

Yes, it's unfortunately a known bugs with Python 3.8 : https://forum.deluge-torrent.org/viewtopic.php?t=55673

It's only affecting translations, but I can understand if it's a showstopper

2021-02-25 17:32 UTC, aptalca commented
wow, just realized deluge hasn't gotten an update since Jun 2019

2021-12-18 16:58 UTC, michaelkrieger commented
This is still a big showstopper now with more recent bugs in the 1.2 branch.  Any updates on seeing the base system updated to enable newer versions?

2022-01-15 23:55 UTC, closed without merging